[project]
name = "r2r"
version = "0.1.0"
description = ""
authors = []
requires-python = ">=3.10,<3.11"
dependencies = [
    "audiosr==0.0.7",
    "deepfilternet==0.5.6",
    "numpy==1.23.5",
    "torch==2.2.2",
    "torchaudio==2.2.2",
    "torchvision==0.17.2"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"